# Generated by Django 5.2.3 on 2025-06-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='description',
            field=models.CharField(blank=True, default=None, null=True, max_length=255),
        ),
    ]
